imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_admin.config.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Doctrine mongodb Configuration
doctrine_mongodb:
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: "%mongodb_server%"
            options:
              username: "%mongodb_username%"
              password: "%mongodb_password%"
              db: "%mongodb_db%"
    default_database: hello_%kernel.environment%
    default_database: "%mongodb_db%"
    document_managers:
        default:
            mappings:
                SonataUserBundle: ~
                FOSUserBundle: ~
            auto_mapping: true


fos_oauth_server:
    db_driver: mongodb
    client_class:        Offy\Bundle\UserBundle\Document\Client
    access_token_class:  Offy\Bundle\UserBundle\Document\AccessToken
    refresh_token_class: Offy\Bundle\UserBundle\Document\RefreshToken
    auth_code_class:     Offy\Bundle\UserBundle\Document\AuthCode
    service:
        user_provider: platform.user.provider
        options :
            supported_scopes: user
            access_token_lifetime: 7776000

# fos_user:
#     db_driver: mongodb
#     firewall_name: main
#     user_class: Offy\Bundle\UserBundle\Document\User
#     service:
#         mailer:  fos_user.mailer.twig_swift
#     from_email:
#         address:        tainb92@gmail.com
#         sender_name:    Tai Nguyen
#     registration:
#         form:
#             type: fos_user_rest_registration
#         confirmation:
#             from_email:
#                 address:        registration@example.com
#                 sender_name:    Demo Registration

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: force
        formats:
            xml: true
            json : true
        templating_formats:
            html: false
    routing_loader:
        default_format: json

nelmio_api_doc:
    sandbox:
        authentication:
            name: access_token
            delivery: query

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            hosts: ['^api\.']


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
