services:
#    tainb_category.example:
#        class: Tainb\Bundle\CategoryBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    admin.category:
            class: Tainb\Bundle\CategoryBundle\Admin\CategoryAdmin
            arguments: [~, Tainb\Bundle\CategoryBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Category, group: 'Category Management' }

    category.listener:
            class: Tainb\Bundle\CategoryBundle\Listener\EventListener
            tags:
                - { name: doctrine.event_listener, event: prePersist  }